### PR TITLE
fix(mission-runtime-creatapp): hide more option if description have l…

### PR DESCRIPTION
**Pull request by vikram-raj**
…ess then 55 character

Fixes https://github.com/openshiftio/openshift.io/issues/3443

### CODE REVIEW

**Comment by invincibleJai** [comment]
good to have 60, even 55 looks fine to me.

**Comment by vikram-raj** [comment]
55 looks fine to me. 60 or 65 doesn't make much difference. And anyway we are giving the option to show more and less to the user.

**Comment by ia3andy** [comment]
@vikram-raj 

I know it's content dependent, but it a shame to have the more on this one for example:

image
image

**Comment by vikram-raj** [comment]
@ia3andy Yes, agree in this case. Should I increase the limit to 65 in this PR?

**Comment by ia3andy** [comment]
@vikram-raj make a new PR ;)

**Pull request merged**
