### PR TITLE
Made target environment the first step

### PR DESCRIPTION
**Pull request by edewit**
Selecting a cluster for "launch" is now more close to the new design:
https://redhat.invisionapp.com/share/67HOQB7UCB9#/screens/294121665

### CODE REVIEW

**Comment by edewit** [comment]
to see this in action select a cluster and then the 'CRUD' mission 'Vert.x' will be disabled because of to little resources to run that booster.

**Comment by jyasveer** [comment]
@edewit 
I had approved this PR as the code looked fine to me. However, I am seeing a bug with this PR. Now when I took the latest changes from master and tested in fabric8-ui, i saw that, the arrow button in the mission-runtime screen does not work for the first time. I think the animations is broken. Can you please have a look ?
You can find the behaviour here in this video https://drive.google.com/open?id=1eVSS8oYgZpPWl6mULTNO7HTayvXqs5-R

**Comment by edewit** [comment]
It's due to the fact that the TargetRuntime is now the first step, sorry
about this investigating how to solve this

**Comment by jyasveer** [comment]
> It's due to the fact that the TargetRuntime is now the first step, sorry
about this investigating how to solve this

Thanks

**Pull request merged**
