### PR TITLE
Initial version of the new mission runtime screen

### PR DESCRIPTION
**Pull request by edewit**
this might move to standalone launcher just a PR now for testing

### CODE REVIEW

**Comment by edewit** [comment]
Screenshot, didn't do much styling yet, this PR is just to try out how it works
screenshot from 2018-10-30 14-12-15

**Comment by edewit** [comment]
initial stab at issue https://github.com/fabric8-launcher/launcher-frontend/issues/587

**Comment by ia3andy** [comment]
@edewit I really like the xp :) As you said it lacks some design.

**Comment by edewit** [comment]
@vikram-raj our list of "missions" is very long and we wanted to change the way this page works, is it okay for OSIO as well?

**Comment by vikram-raj** [comment]
@edewit Do you have UXD for this. Because we need to verify this changes with our UXD team.

**Comment by edewit** [comment]
@vikram-raj this is something we came up with ourselves.

**Comment by vikram-raj** [comment]
@edewit We will get review it from our UX team before getting it in the OSIO.

**Comment by vikram-raj** [comment]
@edewit For now, can we keep both components the current one and this new one?

**Comment by edewit** [comment]
yes, will update this PR

**Comment by edewit** [comment]
it's done currently it looks like this:
screenshot from 2018-11-20 15-32-46

**Comment by edewit** [comment]
For now moved this to [`launcher-frontend`](https://github.com/fabric8-launcher/launcher-frontend/pull/761)

**Pull request closed without merging**
