### PR TITLE
Revert "fix(telemetry): Added code for telemetry"

### PR DESCRIPTION
**Pull request by edewit**
Reverts fabric8-launcher/ngx-launcher#273

### CODE REVIEW

**Comment by edewit** [comment]
need to revert this, because it's breaking launch and don't think using home grown events should be used to gather telemetry better to use products that we already use.

**Comment by gastaldi** [comment]
Fixes https://github.com/fabric8-launcher/launcher-frontend/issues/489

**Comment by jyasveer** [comment]
@edewit I haven't used `ngx-base` here in this PR, that can break launch.
And as per the events we have to use, these events can be custom user events which segment can understand. We use api's of segment to register them along with the user data. Something like here https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/analytics.service.ts#L56

**Pull request merged**
