### PR TITLE
fix: Some missions are not selectable when runtime is selected

### LINKED ISSUE #349: Some missions are not selectable when runtime is selected
This is causing this bug in OSIO: https://github.com/openshiftio/openshift.io/issues/3997#issuecomment-411332678

And in Launcher flow, it makes the UI weird.

- Version selection should not affect available missions.
- Selecting a Mission should auto change the selected version based on availability

I suggest to make the two UIs a bit more similar by changing the way we show the version combobox.
We give the user the possibility to change version only when the mission and runtime are selected with a new "Select Version" button (in place of the combobox) that when clicked show the combobox.

if the user does and change the mission, it auto switches back to "select version" button (so the user can see that his selection has been lost).

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #349

### CODE REVIEW

**Comment by gastaldi** [comment]
Quoting @bartoszmajsak: 
> some test would be nice :stuck_out_tongue:

**Comment by ia3andy** [comment]
I could check that:
 - the combobox is only visible when you select mission and runtime
- the runtime get auto-deselected if you choose a non-compatible mission

@gastaldi @bartoszmajsak do you see some other cases to test ?

**Comment by bartoszmajsak** [comment]
@ia3andy I think that is fair enough for now. Might be something for our e2e tests in OSIO going further.

I assume that solves https://github.com/openshiftio/openshift.io/issues/3997 too?

**Comment by bartoszmajsak** [comment]
> It does, maybe you guys still should talk about catalog versions, because I think it's a still a bit weird to have different runtime versions for different missions

Yeah, I'm on it.

**Comment by bartoszmajsak** [comment]
So I tested it against OSIO catalog and it seems to be working fine. No weird side effects. Now... waiting for tests :)

**Comment by ia3andy** [comment]
I am currently adding and cleaning tests

**Pull request merged**
