### PR TITLE
fix(telemetry): pass broadcaster instance to dep editor component

### PR DESCRIPTION
**Pull request by jyasveer**
1. This PR is to make the broadcaster instance available in the dependency editor module.
2. Depends on https://github.com/fabric8-analytics/fabric8-analytics-dependency-editor/pull/111. This is merged now
3. Need to update the dep-editor version once point 2 is merged and a new version is release successfully

### CODE REVIEW

**Comment by jyasveer** [comment]
I updated the dep-editor version to 0.7.2

**Comment by jyasveer** [comment]
@invincibleJai can you please review this PR ?

**Comment by invincibleJai** [comment]
Thanks @jyasveer

**Pull request merged**
