### PR TITLE
fix: multiple bugs in osio mission/runtime step

### PR DESCRIPTION
**Pull request by ia3andy**
- Fix bug in `DependencyEditorCreateappStepComponent` if `depEditorService` is not defined (optional)
- Fix osio catalog data consistency bug in demo (blank mission)
- Update osio demo catalog data

### CODE REVIEW

**Comment by invincibleJai** [comment]
@ia3andy code looks good, let me check out locally and try.

**Comment by bartoszmajsak** [comment]
Fixes https://github.com/openshiftio/openshift.io/issues/4110

**Comment by ia3andy** [comment]
There is a small bug in a test, I am on it

**Comment by ia3andy** [comment]
Fixed :)

**Comment by invincibleJai** [comment]
Tested with OSIO , looks good !!

**Pull request merged**
