### PR TITLE
fix(npm): move forge related components inside ngx-forge

### PR DESCRIPTION
**Pull request by arunkumars08**
Moves the following:
1. forge-errors
2. forge-exception
3. spinner
4. multiple-selection-list
5. single-selection-dropdown
6. pipeline-view

adds stylesheets

### CODE REVIEW

**Comment by arunkumars08** [comment]
This PR tracks this user story - https://github.com/openshiftio/openshift.io/issues/1186

Once merged here, changes have to be made on Fabric8-ui to import these components

**Comment by edewit** [comment]
Some tests would be nice

**Comment by edewit** [comment]
👍 what do you think @corinnekrych

**Comment by corinnekrych** [comment]
I think to we should add component testing. As areference, see:
- component test example in [fabric8-ui / codebase module](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/create/codebases/codebases-add/codebases-add.component.spec.ts)
- Bartosz did this PR using [a testing tools pattern](https://github.com/fabric8-ui/fabric8-ui/pull/2234)

**Comment by corinnekrych** [comment]
@arunkumars08 here is a PR with my review: https://github.com/arunkumars08/ngx-forge/pull/1

**Pull request merged**
