### PR TITLE
fix(improvement): Get rid of a api call to get booster

### PR DESCRIPTION
**Pull request by jyasveer**
solves this issue :- https://github.com/openshiftio/openshift.io/issues/3873

### CODE REVIEW

**Comment by edewit** [comment]
:+1:

**Comment by arunkumars08** [comment]
@jyasveer @edewit Any reason why dependency editor related things are removed?

**Comment by edewit** [comment]
@arunkumars08 it's done because of [this issue](https://github.com/openshiftio/openshift.io/issues/3873)?

**Pull request merged**
