### PR TITLE
fix(telemetry): Added code for telemetry

### PR DESCRIPTION
**Pull request by jyasveer**
user story :- https://github.com/openshiftio/openshift.io/issues/3241

### CODE REVIEW

**Comment by edewit** [comment]
@jyasveer if you want to go back to `ngx-base` please also remove the `BroadcastService` as this is now duplicated. I am wondering why / what you did to make this work without the PR on ngx-base?

**Comment by jyasveer** [comment]
@edewit @ia3andy I did not do anything. It worked for me since last Friday with the broadcaster service from ngx-base.

**Comment by jyasveer** [comment]
@edewit @ia3andy this PR does not depend on `ngx-base` at all. I am using the broadcaster service from the launcher repo itself

**Comment by edewit** [comment]
:+1:

**Comment by jyasveer** [comment]
@edewit let me have a look

**Comment by jyasveer** [comment]
@edewit i have updated the specs and you are good to go to merge if you find the PR okay

**Pull request merged**
