### PR TITLE
Introduced custom validator

### PR DESCRIPTION
**Pull request by edewit**
Added bonus is the ability to see if forms are valid

part of https://github.com/fabric8-launcher/ngx-launcher/issues/216

@ia3andy step one

### CODE REVIEW

**Comment by jyasveer** [comment]
@edewit can you please change the commit message to support semantic release. For eg: `fix(something): <message>`

**Comment by invincibleJai** [comment]
@edewit needed help here, I tried testing it locally with linking to fabric8-ui

1. GitHub repo name is not getting validated looks like.

screen shot 2018-05-23 at 2 21 24 pm

2. Even Login and Authorize was not working  for gitHub

**Comment by edewit** [comment]
@invincibleJai could you tell me how to reproduce that when I do the following:
```
$ ngx-forge> npm link
$ ngx-forge> cd ../fabric8-ui
$ fabric8-ui> npm link ngx-forge
$ fabric8-ui> npm start
```
I get the following [compile errors ](https://gist.github.com/edewit/a8065881fc056110690eb9b33e049af7)

**Comment by invincibleJai** [comment]
@edewit one more info on this, as of now App Name and repo name has to be same and unique. Can know from here 

- https://github.com/openshiftio/openshift.io/issues/3095#issuecomment-386208142
- https://github.com/openshiftio/openshift.io/issues/3432

And this scenario is already implemented for OSIO flow, we need to make sure that these changes doesn't break this.

CC @jyasveer @arunkumars08

**Comment by arunkumars08** [comment]
@edewit If this is also about taking care of same name for both Github and app, could this wait until this - https://github.com/openshiftio/openshift.io/issues/3662? As this will remove the validation of github repo and app name to be same.

**Pull request closed without merging**
