### PR TITLE
fix: don't render artifactId and groupId when runtime is nodejs

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by invincibleJai** [comment]
[test]

**Comment by invincibleJai** [comment]
[test]

**Comment by invincibleJai** [comment]
[test]

**Comment by invincibleJai** [comment]
@edewit one test is failing,

screen shot 2018-05-02 at 3 40 47 pm
 Pls take a look once

**Comment by edewit** [comment]
okay 'runtime' can be undefined of course fixed that thanks

**Comment by jyasveer** [comment]
@edewit can you please resolve the conflicts

**Comment by edewit** [comment]
rebased @jyasveer

**Pull request merged**
